version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_springgg
    restart: always
    environment:
      POSTGRES_DB: springgg
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/springgg?schema=public
    depends_on:
      postgres:
        condition: service_healthy
