services:
  postgres:
    image: postgres:latest
    container_name: postgres_springgg
    restart: always
    environment:
      POSTGRES_DB: springgg
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_springgg
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mail-dev:
    container_name: mail_springgg
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
      
        