import { Navbar } from "@/components/Navbar";
import "./globals.css";
import { NextAuthProvider } from "./providers";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
     <head>
      <link rel="shortcut icon" type="image/x-icon" href="/logo.png" />
      <title>Easy2Code</title>
    </head>
      <body>
      <NextAuthProvider>
      <div className="w-full px-4  md:px-8 lg:px-16 xl:px-28 2xl:px-44  fixed top-0 z-100  bg-gray-100" >
      <Navbar/>
         </div>
         <div className=" bg-gray-100  h-full px-4 md:px-8 lg:px-16  2xl:pr-20 2xl:pl-20 mt-24">
         {children}
         </div>
         <Footer />
         </NextAuthProvider>
      </body>
    </html>
  );
}
